// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "coptr.h"

/////////////////////////////////////////////////////////////////////////////
// CCoptr

IMPLEMENT_DYNCREATE(CCoptr, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CCoptr properties

long CCoptr::GetBinaryConversion()
{
	long result;
	GetProperty(0x1, VT_I4, (void*)&result);
	return result;
}

void CCoptr::SetBinaryConversion(long propVal)
{
	SetProperty(0x1, VT_I4, propVal);
}

CString CCoptr::GetCheckHealthText()
{
	CString result;
	GetProperty(0x2, VT_BSTR, (void*)&result);
	return result;
}

void CCoptr::SetCheckHealthText(LPCTSTR propVal)
{
	SetProperty(0x2, VT_BSTR, propVal);
}

BOOL CCoptr::GetClaimed()
{
	BOOL result;
	GetProperty(0x3, VT_BOOL, (void*)&result);
	return result;
}

void CCoptr::SetClaimed(BOOL propVal)
{
	SetProperty(0x3, VT_BOOL, propVal);
}

BOOL CCoptr::GetDeviceEnabled()
{
	BOOL result;
	GetProperty(0x4, VT_BOOL, (void*)&result);
	return result;
}

void CCoptr::SetDeviceEnabled(BOOL propVal)
{
	SetProperty(0x4, VT_BOOL, propVal);
}

BOOL CCoptr::GetFreezeEvents()
{
	BOOL result;
	GetProperty(0x5, VT_BOOL, (void*)&result);
	return result;
}

void CCoptr::SetFreezeEvents(BOOL propVal)
{
	SetProperty(0x5, VT_BOOL, propVal);
}

long CCoptr::GetOutputID()
{
	long result;
	GetProperty(0x6, VT_I4, (void*)&result);
	return result;
}

void CCoptr::SetOutputID(long propVal)
{
	SetProperty(0x6, VT_I4, propVal);
}

long CCoptr::GetResultCode()
{
	long result;
	GetProperty(0x7, VT_I4, (void*)&result);
	return result;
}

void CCoptr::SetResultCode(long propVal)
{
	SetProperty(0x7, VT_I4, propVal);
}

long CCoptr::GetResultCodeExtended()
{
	long result;
	GetProperty(0x8, VT_I4, (void*)&result);
	return result;
}

void CCoptr::SetResultCodeExtended(long propVal)
{
	SetProperty(0x8, VT_I4, propVal);
}

long CCoptr::GetState()
{
	long result;
	GetProperty(0x9, VT_I4, (void*)&result);
	return result;
}

void CCoptr::SetState(long propVal)
{
	SetProperty(0x9, VT_I4, propVal);
}

CString CCoptr::GetControlObjectDescription()
{
	CString result;
	GetProperty(0xa, VT_BSTR, (void*)&result);
	return result;
}

void CCoptr::SetControlObjectDescription(LPCTSTR propVal)
{
	SetProperty(0xa, VT_BSTR, propVal);
}

long CCoptr::GetControlObjectVersion()
{
	long result;
	GetProperty(0xb, VT_I4, (void*)&result);
	return result;
}

void CCoptr::SetControlObjectVersion(long propVal)
{
	SetProperty(0xb, VT_I4, propVal);
}

CString CCoptr::GetServiceObjectDescription()
{
	CString result;
	GetProperty(0xc, VT_BSTR, (void*)&result);
	return result;
}

void CCoptr::SetServiceObjectDescription(LPCTSTR propVal)
{
	SetProperty(0xc, VT_BSTR, propVal);
}

long CCoptr::GetServiceObjectVersion()
{
	long result;
	GetProperty(0xd, VT_I4, (void*)&result);
	return result;
}

void CCoptr::SetServiceObjectVersion(long propVal)
{
	SetProperty(0xd, VT_I4, propVal);
}

CString CCoptr::GetDeviceDescription()
{
	CString result;
	GetProperty(0xe, VT_BSTR, (void*)&result);
	return result;
}

void CCoptr::SetDeviceDescription(LPCTSTR propVal)
{
	SetProperty(0xe, VT_BSTR, propVal);
}

CString CCoptr::GetDeviceName()
{
	CString result;
	GetProperty(0xf, VT_BSTR, (void*)&result);
	return result;
}

void CCoptr::SetDeviceName(LPCTSTR propVal)
{
	SetProperty(0xf, VT_BSTR, propVal);
}

long CCoptr::GetCapCharacterSet()
{
	long result;
	GetProperty(0x10, VT_I4, (void*)&result);
	return result;
}

void CCoptr::SetCapCharacterSet(long propVal)
{
	SetProperty(0x10, VT_I4, propVal);
}

BOOL CCoptr::GetCapConcurrentJrnRec()
{
	BOOL result;
	GetProperty(0x11, VT_BOOL, (void*)&result);
	return result;
}

void CCoptr::SetCapConcurrentJrnRec(BOOL propVal)
{
	SetProperty(0x11, VT_BOOL, propVal);
}

BOOL CCoptr::GetCapConcurrentJrnSlp()
{
	BOOL result;
	GetProperty(0x12, VT_BOOL, (void*)&result);
	return result;
}

void CCoptr::SetCapConcurrentJrnSlp(BOOL propVal)
{
	SetProperty(0x12, VT_BOOL, propVal);
}

BOOL CCoptr::GetCapConcurrentRecSlp()
{
	BOOL result;
	GetProperty(0x13, VT_BOOL, (void*)&result);
	return result;
}

void CCoptr::SetCapConcurrentRecSlp(BOOL propVal)
{
	SetProperty(0x13, VT_BOOL, propVal);
}

BOOL CCoptr::GetCapCoverSensor()
{
	BOOL result;
	GetProperty(0x14, VT_BOOL, (void*)&result);
	return result;
}

void CCoptr::SetCapCoverSensor(BOOL propVal)
{
	SetProperty(0x14, VT_BOOL, propVal);
}

BOOL CCoptr::GetCapTransaction()
{
	BOOL result;
	GetProperty(0x15, VT_BOOL, (void*)&result);
	return result;
}

void CCoptr::SetCapTransaction(BOOL propVal)
{
	SetProperty(0x15, VT_BOOL, propVal);
}

BOOL CCoptr::GetCapJrnPresent()
{
	BOOL result;
	GetProperty(0x16, VT_BOOL, (void*)&result);
	return result;
}

void CCoptr::SetCapJrnPresent(BOOL propVal)
{
	SetProperty(0x16, VT_BOOL, propVal);
}

BOOL CCoptr::GetCapJrn2Color()
{
	BOOL result;
	GetProperty(0x17, VT_BOOL, (void*)&result);
	return result;
}

void CCoptr::SetCapJrn2Color(BOOL propVal)
{
	SetProperty(0x17, VT_BOOL, propVal);
}

BOOL CCoptr::GetCapJrnBold()
{
	BOOL result;
	GetProperty(0x18, VT_BOOL, (void*)&result);
	return result;
}

void CCoptr::SetCapJrnBold(BOOL propVal)
{
	SetProperty(0x18, VT_BOOL, propVal);
}

BOOL CCoptr::GetCapJrnDhigh()
{
	BOOL result;
	GetProperty(0x19, VT_BOOL, (void*)&result);
	return result;
}

void CCoptr::SetCapJrnDhigh(BOOL propVal)
{
	SetProperty(0x19, VT_BOOL, propVal);
}

BOOL CCoptr::GetCapJrnDwide()
{
	BOOL result;
	GetProperty(0x1a, VT_BOOL, (void*)&result);
	return result;
}

void CCoptr::SetCapJrnDwide(BOOL propVal)
{
	SetProperty(0x1a, VT_BOOL, propVal);
}

BOOL CCoptr::GetCapJrnDwideDhigh()
{
	BOOL result;
	GetProperty(0x1b, VT_BOOL, (void*)&result);
	return result;
}

void CCoptr::SetCapJrnDwideDhigh(BOOL propVal)
{
	SetProperty(0x1b, VT_BOOL, propVal);
}

BOOL CCoptr::GetCapJrnEmptySensor()
{
	BOOL result;
	GetProperty(0x1c, VT_BOOL, (void*)&result);
	return result;
}

void CCoptr::SetCapJrnEmptySensor(BOOL propVal)
{
	SetProperty(0x1c, VT_BOOL, propVal);
}

BOOL CCoptr::GetCapJrnItalic()
{
	BOOL result;
	GetProperty(0x1d, VT_BOOL, (void*)&result);
	return result;
}

void CCoptr::SetCapJrnItalic(BOOL propVal)
{
	SetProperty(0x1d, VT_BOOL, propVal);
}

BOOL CCoptr::GetCapJrnNearEndSensor()
{
	BOOL result;
	GetProperty(0x1e, VT_BOOL, (void*)&result);
	return result;
}

void CCoptr::SetCapJrnNearEndSensor(BOOL propVal)
{
	SetProperty(0x1e, VT_BOOL, propVal);
}

BOOL CCoptr::GetCapJrnUnderline()
{
	BOOL result;
	GetProperty(0x1f, VT_BOOL, (void*)&result);
	return result;
}

void CCoptr::SetCapJrnUnderline(BOOL propVal)
{
	SetProperty(0x1f, VT_BOOL, propVal);
}

BOOL CCoptr::GetCapRecPresent()
{
	BOOL result;
	GetProperty(0x20, VT_BOOL, (void*)&result);
	return result;
}

void CCoptr::SetCapRecPresent(BOOL propVal)
{
	SetProperty(0x20, VT_BOOL, propVal);
}

BOOL CCoptr::GetCapRec2Color()
{
	BOOL result;
	GetProperty(0x21, VT_BOOL, (void*)&result);
	return result;
}

void CCoptr::SetCapRec2Color(BOOL propVal)
{
	SetProperty(0x21, VT_BOOL, propVal);
}

BOOL CCoptr::GetCapRecBarCode()
{
	BOOL result;
	GetProperty(0x22, VT_BOOL, (void*)&result);
	return result;
}

void CCoptr::SetCapRecBarCode(BOOL propVal)
{
	SetProperty(0x22, VT_BOOL, propVal);
}

BOOL CCoptr::GetCapRecBitmap()
{
	BOOL result;
	GetProperty(0x23, VT_BOOL, (void*)&result);
	return result;
}

void CCoptr::SetCapRecBitmap(BOOL propVal)
{
	SetProperty(0x23, VT_BOOL, propVal);
}

BOOL CCoptr::GetCapRecBold()
{
	BOOL result;
	GetProperty(0x24, VT_BOOL, (void*)&result);
	return result;
}

void CCoptr::SetCapRecBold(BOOL propVal)
{
	SetProperty(0x24, VT_BOOL, propVal);
}

BOOL CCoptr::GetCapRecDhigh()
{
	BOOL result;
	GetProperty(0x25, VT_BOOL, (void*)&result);
	return result;
}

void CCoptr::SetCapRecDhigh(BOOL propVal)
{
	SetProperty(0x25, VT_BOOL, propVal);
}

BOOL CCoptr::GetCapRecDwide()
{
	BOOL result;
	GetProperty(0x26, VT_BOOL, (void*)&result);
	return result;
}

void CCoptr::SetCapRecDwide(BOOL propVal)
{
	SetProperty(0x26, VT_BOOL, propVal);
}

BOOL CCoptr::GetCapRecDwideDhigh()
{
	BOOL result;
	GetProperty(0x27, VT_BOOL, (void*)&result);
	return result;
}

void CCoptr::SetCapRecDwideDhigh(BOOL propVal)
{
	SetProperty(0x27, VT_BOOL, propVal);
}

BOOL CCoptr::GetCapRecEmptySensor()
{
	BOOL result;
	GetProperty(0x28, VT_BOOL, (void*)&result);
	return result;
}

void CCoptr::SetCapRecEmptySensor(BOOL propVal)
{
	SetProperty(0x28, VT_BOOL, propVal);
}

BOOL CCoptr::GetCapRecItalic()
{
	BOOL result;
	GetProperty(0x29, VT_BOOL, (void*)&result);
	return result;
}

void CCoptr::SetCapRecItalic(BOOL propVal)
{
	SetProperty(0x29, VT_BOOL, propVal);
}

BOOL CCoptr::GetCapRecLeft90()
{
	BOOL result;
	GetProperty(0x2a, VT_BOOL, (void*)&result);
	return result;
}

void CCoptr::SetCapRecLeft90(BOOL propVal)
{
	SetProperty(0x2a, VT_BOOL, propVal);
}

BOOL CCoptr::GetCapRecNearEndSensor()
{
	BOOL result;
	GetProperty(0x2b, VT_BOOL, (void*)&result);
	return result;
}

void CCoptr::SetCapRecNearEndSensor(BOOL propVal)
{
	SetProperty(0x2b, VT_BOOL, propVal);
}

BOOL CCoptr::GetCapRecPapercut()
{
	BOOL result;
	GetProperty(0x2c, VT_BOOL, (void*)&result);
	return result;
}

void CCoptr::SetCapRecPapercut(BOOL propVal)
{
	SetProperty(0x2c, VT_BOOL, propVal);
}

BOOL CCoptr::GetCapRecRight90()
{
	BOOL result;
	GetProperty(0x2d, VT_BOOL, (void*)&result);
	return result;
}

void CCoptr::SetCapRecRight90(BOOL propVal)
{
	SetProperty(0x2d, VT_BOOL, propVal);
}

BOOL CCoptr::GetCapRecRotate180()
{
	BOOL result;
	GetProperty(0x2e, VT_BOOL, (void*)&result);
	return result;
}

void CCoptr::SetCapRecRotate180(BOOL propVal)
{
	SetProperty(0x2e, VT_BOOL, propVal);
}

BOOL CCoptr::GetCapRecStamp()
{
	BOOL result;
	GetProperty(0x2f, VT_BOOL, (void*)&result);
	return result;
}

void CCoptr::SetCapRecStamp(BOOL propVal)
{
	SetProperty(0x2f, VT_BOOL, propVal);
}

BOOL CCoptr::GetCapRecUnderline()
{
	BOOL result;
	GetProperty(0x30, VT_BOOL, (void*)&result);
	return result;
}

void CCoptr::SetCapRecUnderline(BOOL propVal)
{
	SetProperty(0x30, VT_BOOL, propVal);
}

BOOL CCoptr::GetCapSlpPresent()
{
	BOOL result;
	GetProperty(0x31, VT_BOOL, (void*)&result);
	return result;
}

void CCoptr::SetCapSlpPresent(BOOL propVal)
{
	SetProperty(0x31, VT_BOOL, propVal);
}

BOOL CCoptr::GetCapSlpFullslip()
{
	BOOL result;
	GetProperty(0x32, VT_BOOL, (void*)&result);
	return result;
}

void CCoptr::SetCapSlpFullslip(BOOL propVal)
{
	SetProperty(0x32, VT_BOOL, propVal);
}

BOOL CCoptr::GetCapSlp2Color()
{
	BOOL result;
	GetProperty(0x33, VT_BOOL, (void*)&result);
	return result;
}

void CCoptr::SetCapSlp2Color(BOOL propVal)
{
	SetProperty(0x33, VT_BOOL, propVal);
}

BOOL CCoptr::GetCapSlpBarCode()
{
	BOOL result;
	GetProperty(0x34, VT_BOOL, (void*)&result);
	return result;
}

void CCoptr::SetCapSlpBarCode(BOOL propVal)
{
	SetProperty(0x34, VT_BOOL, propVal);
}

BOOL CCoptr::GetCapSlpBitmap()
{
	BOOL result;
	GetProperty(0x35, VT_BOOL, (void*)&result);
	return result;
}

void CCoptr::SetCapSlpBitmap(BOOL propVal)
{
	SetProperty(0x35, VT_BOOL, propVal);
}

BOOL CCoptr::GetCapSlpBold()
{
	BOOL result;
	GetProperty(0x36, VT_BOOL, (void*)&result);
	return result;
}

void CCoptr::SetCapSlpBold(BOOL propVal)
{
	SetProperty(0x36, VT_BOOL, propVal);
}

BOOL CCoptr::GetCapSlpDhigh()
{
	BOOL result;
	GetProperty(0x37, VT_BOOL, (void*)&result);
	return result;
}

void CCoptr::SetCapSlpDhigh(BOOL propVal)
{
	SetProperty(0x37, VT_BOOL, propVal);
}

BOOL CCoptr::GetCapSlpDwide()
{
	BOOL result;
	GetProperty(0x38, VT_BOOL, (void*)&result);
	return result;
}

void CCoptr::SetCapSlpDwide(BOOL propVal)
{
	SetProperty(0x38, VT_BOOL, propVal);
}

BOOL CCoptr::GetCapSlpDwideDhigh()
{
	BOOL result;
	GetProperty(0x39, VT_BOOL, (void*)&result);
	return result;
}

void CCoptr::SetCapSlpDwideDhigh(BOOL propVal)
{
	SetProperty(0x39, VT_BOOL, propVal);
}

BOOL CCoptr::GetCapSlpEmptySensor()
{
	BOOL result;
	GetProperty(0x3a, VT_BOOL, (void*)&result);
	return result;
}

void CCoptr::SetCapSlpEmptySensor(BOOL propVal)
{
	SetProperty(0x3a, VT_BOOL, propVal);
}

BOOL CCoptr::GetCapSlpItalic()
{
	BOOL result;
	GetProperty(0x3b, VT_BOOL, (void*)&result);
	return result;
}

void CCoptr::SetCapSlpItalic(BOOL propVal)
{
	SetProperty(0x3b, VT_BOOL, propVal);
}

BOOL CCoptr::GetCapSlpLeft90()
{
	BOOL result;
	GetProperty(0x3c, VT_BOOL, (void*)&result);
	return result;
}

void CCoptr::SetCapSlpLeft90(BOOL propVal)
{
	SetProperty(0x3c, VT_BOOL, propVal);
}

BOOL CCoptr::GetCapSlpNearEndSensor()
{
	BOOL result;
	GetProperty(0x3d, VT_BOOL, (void*)&result);
	return result;
}

void CCoptr::SetCapSlpNearEndSensor(BOOL propVal)
{
	SetProperty(0x3d, VT_BOOL, propVal);
}

BOOL CCoptr::GetCapSlpRight90()
{
	BOOL result;
	GetProperty(0x3e, VT_BOOL, (void*)&result);
	return result;
}

void CCoptr::SetCapSlpRight90(BOOL propVal)
{
	SetProperty(0x3e, VT_BOOL, propVal);
}

BOOL CCoptr::GetCapSlpRotate180()
{
	BOOL result;
	GetProperty(0x3f, VT_BOOL, (void*)&result);
	return result;
}

void CCoptr::SetCapSlpRotate180(BOOL propVal)
{
	SetProperty(0x3f, VT_BOOL, propVal);
}

BOOL CCoptr::GetCapSlpUnderline()
{
	BOOL result;
	GetProperty(0x40, VT_BOOL, (void*)&result);
	return result;
}

void CCoptr::SetCapSlpUnderline(BOOL propVal)
{
	SetProperty(0x40, VT_BOOL, propVal);
}

BOOL CCoptr::GetAsyncMode()
{
	BOOL result;
	GetProperty(0x41, VT_BOOL, (void*)&result);
	return result;
}

void CCoptr::SetAsyncMode(BOOL propVal)
{
	SetProperty(0x41, VT_BOOL, propVal);
}

long CCoptr::GetCharacterSet()
{
	long result;
	GetProperty(0x42, VT_I4, (void*)&result);
	return result;
}

void CCoptr::SetCharacterSet(long propVal)
{
	SetProperty(0x42, VT_I4, propVal);
}

CString CCoptr::GetCharacterSetList()
{
	CString result;
	GetProperty(0x43, VT_BSTR, (void*)&result);
	return result;
}

void CCoptr::SetCharacterSetList(LPCTSTR propVal)
{
	SetProperty(0x43, VT_BSTR, propVal);
}

BOOL CCoptr::GetCoverOpen()
{
	BOOL result;
	GetProperty(0x44, VT_BOOL, (void*)&result);
	return result;
}

void CCoptr::SetCoverOpen(BOOL propVal)
{
	SetProperty(0x44, VT_BOOL, propVal);
}

long CCoptr::GetErrorLevel()
{
	long result;
	GetProperty(0x45, VT_I4, (void*)&result);
	return result;
}

void CCoptr::SetErrorLevel(long propVal)
{
	SetProperty(0x45, VT_I4, propVal);
}

long CCoptr::GetErrorStation()
{
	long result;
	GetProperty(0x46, VT_I4, (void*)&result);
	return result;
}

void CCoptr::SetErrorStation(long propVal)
{
	SetProperty(0x46, VT_I4, propVal);
}

CString CCoptr::GetErrorString()
{
	CString result;
	GetProperty(0x47, VT_BSTR, (void*)&result);
	return result;
}

void CCoptr::SetErrorString(LPCTSTR propVal)
{
	SetProperty(0x47, VT_BSTR, propVal);
}

BOOL CCoptr::GetFlagWhenIdle()
{
	BOOL result;
	GetProperty(0x48, VT_BOOL, (void*)&result);
	return result;
}

void CCoptr::SetFlagWhenIdle(BOOL propVal)
{
	SetProperty(0x48, VT_BOOL, propVal);
}

CString CCoptr::GetFontTypefaceList()
{
	CString result;
	GetProperty(0x49, VT_BSTR, (void*)&result);
	return result;
}

void CCoptr::SetFontTypefaceList(LPCTSTR propVal)
{
	SetProperty(0x49, VT_BSTR, propVal);
}

long CCoptr::GetMapMode()
{
	long result;
	GetProperty(0x4a, VT_I4, (void*)&result);
	return result;
}

void CCoptr::SetMapMode(long propVal)
{
	SetProperty(0x4a, VT_I4, propVal);
}

long CCoptr::GetRotateSpecial()
{
	long result;
	GetProperty(0x4b, VT_I4, (void*)&result);
	return result;
}

void CCoptr::SetRotateSpecial(long propVal)
{
	SetProperty(0x4b, VT_I4, propVal);
}

long CCoptr::GetJrnLineChars()
{
	long result;
	GetProperty(0x4c, VT_I4, (void*)&result);
	return result;
}

void CCoptr::SetJrnLineChars(long propVal)
{
	SetProperty(0x4c, VT_I4, propVal);
}

CString CCoptr::GetJrnLineCharsList()
{
	CString result;
	GetProperty(0x4d, VT_BSTR, (void*)&result);
	return result;
}

void CCoptr::SetJrnLineCharsList(LPCTSTR propVal)
{
	SetProperty(0x4d, VT_BSTR, propVal);
}

long CCoptr::GetJrnLineHeight()
{
	long result;
	GetProperty(0x4e, VT_I4, (void*)&result);
	return result;
}

void CCoptr::SetJrnLineHeight(long propVal)
{
	SetProperty(0x4e, VT_I4, propVal);
}

long CCoptr::GetJrnLineSpacing()
{
	long result;
	GetProperty(0x4f, VT_I4, (void*)&result);
	return result;
}

void CCoptr::SetJrnLineSpacing(long propVal)
{
	SetProperty(0x4f, VT_I4, propVal);
}

long CCoptr::GetJrnLineWidth()
{
	long result;
	GetProperty(0x50, VT_I4, (void*)&result);
	return result;
}

void CCoptr::SetJrnLineWidth(long propVal)
{
	SetProperty(0x50, VT_I4, propVal);
}

BOOL CCoptr::GetJrnLetterQuality()
{
	BOOL result;
	GetProperty(0x51, VT_BOOL, (void*)&result);
	return result;
}

void CCoptr::SetJrnLetterQuality(BOOL propVal)
{
	SetProperty(0x51, VT_BOOL, propVal);
}

BOOL CCoptr::GetJrnEmpty()
{
	BOOL result;
	GetProperty(0x52, VT_BOOL, (void*)&result);
	return result;
}

void CCoptr::SetJrnEmpty(BOOL propVal)
{
	SetProperty(0x52, VT_BOOL, propVal);
}

BOOL CCoptr::GetJrnNearEnd()
{
	BOOL result;
	GetProperty(0x53, VT_BOOL, (void*)&result);
	return result;
}

void CCoptr::SetJrnNearEnd(BOOL propVal)
{
	SetProperty(0x53, VT_BOOL, propVal);
}

long CCoptr::GetRecLineChars()
{
	long result;
	GetProperty(0x54, VT_I4, (void*)&result);
	return result;
}

void CCoptr::SetRecLineChars(long propVal)
{
	SetProperty(0x54, VT_I4, propVal);
}

CString CCoptr::GetRecLineCharsList()
{
	CString result;
	GetProperty(0x55, VT_BSTR, (void*)&result);
	return result;
}

void CCoptr::SetRecLineCharsList(LPCTSTR propVal)
{
	SetProperty(0x55, VT_BSTR, propVal);
}

long CCoptr::GetRecLineHeight()
{
	long result;
	GetProperty(0x56, VT_I4, (void*)&result);
	return result;
}

void CCoptr::SetRecLineHeight(long propVal)
{
	SetProperty(0x56, VT_I4, propVal);
}

long CCoptr::GetRecLineSpacing()
{
	long result;
	GetProperty(0x57, VT_I4, (void*)&result);
	return result;
}

void CCoptr::SetRecLineSpacing(long propVal)
{
	SetProperty(0x57, VT_I4, propVal);
}

long CCoptr::GetRecLineWidth()
{
	long result;
	GetProperty(0x58, VT_I4, (void*)&result);
	return result;
}

void CCoptr::SetRecLineWidth(long propVal)
{
	SetProperty(0x58, VT_I4, propVal);
}

BOOL CCoptr::GetRecLetterQuality()
{
	BOOL result;
	GetProperty(0x59, VT_BOOL, (void*)&result);
	return result;
}

void CCoptr::SetRecLetterQuality(BOOL propVal)
{
	SetProperty(0x59, VT_BOOL, propVal);
}

BOOL CCoptr::GetRecEmpty()
{
	BOOL result;
	GetProperty(0x5a, VT_BOOL, (void*)&result);
	return result;
}

void CCoptr::SetRecEmpty(BOOL propVal)
{
	SetProperty(0x5a, VT_BOOL, propVal);
}

BOOL CCoptr::GetRecNearEnd()
{
	BOOL result;
	GetProperty(0x5b, VT_BOOL, (void*)&result);
	return result;
}

void CCoptr::SetRecNearEnd(BOOL propVal)
{
	SetProperty(0x5b, VT_BOOL, propVal);
}

long CCoptr::GetRecSidewaysMaxLines()
{
	long result;
	GetProperty(0x5c, VT_I4, (void*)&result);
	return result;
}

void CCoptr::SetRecSidewaysMaxLines(long propVal)
{
	SetProperty(0x5c, VT_I4, propVal);
}

long CCoptr::GetRecSidewaysMaxChars()
{
	long result;
	GetProperty(0x5d, VT_I4, (void*)&result);
	return result;
}

void CCoptr::SetRecSidewaysMaxChars(long propVal)
{
	SetProperty(0x5d, VT_I4, propVal);
}

long CCoptr::GetRecLinesToPaperCut()
{
	long result;
	GetProperty(0x5e, VT_I4, (void*)&result);
	return result;
}

void CCoptr::SetRecLinesToPaperCut(long propVal)
{
	SetProperty(0x5e, VT_I4, propVal);
}

CString CCoptr::GetRecBarCodeRotationList()
{
	CString result;
	GetProperty(0x5f, VT_BSTR, (void*)&result);
	return result;
}

void CCoptr::SetRecBarCodeRotationList(LPCTSTR propVal)
{
	SetProperty(0x5f, VT_BSTR, propVal);
}

long CCoptr::GetSlpLineChars()
{
	long result;
	GetProperty(0x60, VT_I4, (void*)&result);
	return result;
}

void CCoptr::SetSlpLineChars(long propVal)
{
	SetProperty(0x60, VT_I4, propVal);
}

CString CCoptr::GetSlpLineCharsList()
{
	CString result;
	GetProperty(0x61, VT_BSTR, (void*)&result);
	return result;
}

void CCoptr::SetSlpLineCharsList(LPCTSTR propVal)
{
	SetProperty(0x61, VT_BSTR, propVal);
}

long CCoptr::GetSlpLineHeight()
{
	long result;
	GetProperty(0x62, VT_I4, (void*)&result);
	return result;
}

void CCoptr::SetSlpLineHeight(long propVal)
{
	SetProperty(0x62, VT_I4, propVal);
}

long CCoptr::GetSlpLineSpacing()
{
	long result;
	GetProperty(0x63, VT_I4, (void*)&result);
	return result;
}

void CCoptr::SetSlpLineSpacing(long propVal)
{
	SetProperty(0x63, VT_I4, propVal);
}

long CCoptr::GetSlpLineWidth()
{
	long result;
	GetProperty(0x64, VT_I4, (void*)&result);
	return result;
}

void CCoptr::SetSlpLineWidth(long propVal)
{
	SetProperty(0x64, VT_I4, propVal);
}

BOOL CCoptr::GetSlpLetterQuality()
{
	BOOL result;
	GetProperty(0x65, VT_BOOL, (void*)&result);
	return result;
}

void CCoptr::SetSlpLetterQuality(BOOL propVal)
{
	SetProperty(0x65, VT_BOOL, propVal);
}

BOOL CCoptr::GetSlpEmpty()
{
	BOOL result;
	GetProperty(0x66, VT_BOOL, (void*)&result);
	return result;
}

void CCoptr::SetSlpEmpty(BOOL propVal)
{
	SetProperty(0x66, VT_BOOL, propVal);
}

BOOL CCoptr::GetSlpNearEnd()
{
	BOOL result;
	GetProperty(0x67, VT_BOOL, (void*)&result);
	return result;
}

void CCoptr::SetSlpNearEnd(BOOL propVal)
{
	SetProperty(0x67, VT_BOOL, propVal);
}

long CCoptr::GetSlpSidewaysMaxLines()
{
	long result;
	GetProperty(0x68, VT_I4, (void*)&result);
	return result;
}

void CCoptr::SetSlpSidewaysMaxLines(long propVal)
{
	SetProperty(0x68, VT_I4, propVal);
}

long CCoptr::GetSlpSidewaysMaxChars()
{
	long result;
	GetProperty(0x69, VT_I4, (void*)&result);
	return result;
}

void CCoptr::SetSlpSidewaysMaxChars(long propVal)
{
	SetProperty(0x69, VT_I4, propVal);
}

long CCoptr::GetSlpMaxLines()
{
	long result;
	GetProperty(0x6a, VT_I4, (void*)&result);
	return result;
}

void CCoptr::SetSlpMaxLines(long propVal)
{
	SetProperty(0x6a, VT_I4, propVal);
}

long CCoptr::GetSlpLinesNearEndToEnd()
{
	long result;
	GetProperty(0x6b, VT_I4, (void*)&result);
	return result;
}

void CCoptr::SetSlpLinesNearEndToEnd(long propVal)
{
	SetProperty(0x6b, VT_I4, propVal);
}

CString CCoptr::GetSlpBarCodeRotationList()
{
	CString result;
	GetProperty(0x6c, VT_BSTR, (void*)&result);
	return result;
}

void CCoptr::SetSlpBarCodeRotationList(LPCTSTR propVal)
{
	SetProperty(0x6c, VT_BSTR, propVal);
}

long CCoptr::GetCapPowerReporting()
{
	long result;
	GetProperty(0x6d, VT_I4, (void*)&result);
	return result;
}

void CCoptr::SetCapPowerReporting(long propVal)
{
	SetProperty(0x6d, VT_I4, propVal);
}

long CCoptr::GetPowerNotify()
{
	long result;
	GetProperty(0x6e, VT_I4, (void*)&result);
	return result;
}

void CCoptr::SetPowerNotify(long propVal)
{
	SetProperty(0x6e, VT_I4, propVal);
}

long CCoptr::GetPowerState()
{
	long result;
	GetProperty(0x6f, VT_I4, (void*)&result);
	return result;
}

void CCoptr::SetPowerState(long propVal)
{
	SetProperty(0x6f, VT_I4, propVal);
}

/////////////////////////////////////////////////////////////////////////////
// CCoptr operations

long CCoptr::Open(LPCTSTR DeviceName)
{
	long result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x70, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		DeviceName);
	return result;
}

long CCoptr::Close()
{
	long result;
	InvokeHelper(0x71, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

long CCoptr::Claim(long Timeout)
{
	long result;
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x72, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		Timeout);
	return result;
}

long CCoptr::Release()
{
	long result;
	InvokeHelper(0x73, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

long CCoptr::CheckHealth(long Level)
{
	long result;
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x74, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		Level);
	return result;
}

long CCoptr::ClearOutput()
{
	long result;
	InvokeHelper(0x75, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

long CCoptr::DirectIO(long Command, long* pData, BSTR* pString)
{
	long result;
	static BYTE parms[] =
		VTS_I4 VTS_PI4 VTS_PBSTR;
	InvokeHelper(0x76, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		Command, pData, pString);
	return result;
}

long CCoptr::PrintNormal(long Station, LPCTSTR Data)
{
	long result;
	static BYTE parms[] =
		VTS_I4 VTS_BSTR;
	InvokeHelper(0x77, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		Station, Data);
	return result;
}

long CCoptr::PrintTwoNormal(long Stations, LPCTSTR Data1, LPCTSTR Data2)
{
	long result;
	static BYTE parms[] =
		VTS_I4 VTS_BSTR VTS_BSTR;
	InvokeHelper(0x78, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		Stations, Data1, Data2);
	return result;
}

long CCoptr::PrintImmediate(long Station, LPCTSTR Data)
{
	long result;
	static BYTE parms[] =
		VTS_I4 VTS_BSTR;
	InvokeHelper(0x79, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		Station, Data);
	return result;
}

long CCoptr::BeginInsertion(long Timeout)
{
	long result;
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x7a, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		Timeout);
	return result;
}

long CCoptr::EndInsertion()
{
	long result;
	InvokeHelper(0x7b, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

long CCoptr::BeginRemoval(long Timeout)
{
	long result;
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x7c, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		Timeout);
	return result;
}

long CCoptr::EndRemoval()
{
	long result;
	InvokeHelper(0x7d, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}
/*
long CCoptr::CutPaper(long Percentage)
{
	long result;
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x7e, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		Percentage);
	return result;
}
*/
long CCoptr::RotatePrint(long Station, long Rotation)
{
	long result;
	static BYTE parms[] =
		VTS_I4 VTS_I4;
	InvokeHelper(0x7f, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		Station, Rotation);
	return result;
}

long CCoptr::PrintBarCode(long Station, LPCTSTR Data, long Symbology, long Height, long Width, long Alignment, long TextPosition)
{
	long result;
	static BYTE parms[] =
		VTS_I4 VTS_BSTR VTS_I4 VTS_I4 VTS_I4 VTS_I4 VTS_I4;
	InvokeHelper(0x80, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		Station, Data, Symbology, Height, Width, Alignment, TextPosition);
	return result;
}

long CCoptr::PrintBitmap(long Station, LPCTSTR FileName, long Width, long Alignment)
{
	long result;
	static BYTE parms[] =
		VTS_I4 VTS_BSTR VTS_I4 VTS_I4;
	InvokeHelper(0x81, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		Station, FileName, Width, Alignment);
	return result;
}

long CCoptr::TransactionPrint(long Station, long Control)
{
	long result;
	static BYTE parms[] =
		VTS_I4 VTS_I4;
	InvokeHelper(0x82, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		Station, Control);
	return result;
}

long CCoptr::ValidateData(long Station, LPCTSTR Data)
{
	long result;
	static BYTE parms[] =
		VTS_I4 VTS_BSTR;
	InvokeHelper(0x83, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		Station, Data);
	return result;
}

long CCoptr::SetBitmap(long BitmapNumber, long Station, LPCTSTR FileName, long Width, long Alignment)
{
	long result;
	static BYTE parms[] =
		VTS_I4 VTS_I4 VTS_BSTR VTS_I4 VTS_I4;
	InvokeHelper(0x84, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		BitmapNumber, Station, FileName, Width, Alignment);
	return result;
}

long CCoptr::SetLogo(long Location, LPCTSTR Data)
{
	long result;
	static BYTE parms[] =
		VTS_I4 VTS_BSTR;
	InvokeHelper(0x85, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		Location, Data);
	return result;
}

void CCoptr::SODirectIO(long EventNumber, long* pData, BSTR* pString)
{
	static BYTE parms[] =
		VTS_I4 VTS_PI4 VTS_PBSTR;
	InvokeHelper(0x86, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 EventNumber, pData, pString);
}

void CCoptr::SOError(long ResultCode, long ResultCodeExtended, long ErrorLocus, long* pErrorResponse)
{
	static BYTE parms[] =
		VTS_I4 VTS_I4 VTS_I4 VTS_PI4;
	InvokeHelper(0x87, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 ResultCode, ResultCodeExtended, ErrorLocus, pErrorResponse);
}

void CCoptr::SOOutputComplete(long OutputID)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x88, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 OutputID);
}

void CCoptr::SOStatusUpdate(long Data)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x89, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 Data);
}

long CCoptr::SOProcessID()
{
	long result;
	InvokeHelper(0x8a, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

void CCoptr::AboutBox()
{
	InvokeHelper(0xfffffdd8, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}
